# Generated by Django 5.1.4 on 2024-12-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_agent_email_alter_agent_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='measurments',
            new_name='measurements',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
