# Generated by Django 5.1.4 on 2024-12-23 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 1, 20, 0)),
            preserve_default=False,
        ),
    ]
