# Generated by Django 5.1.4 on 2025-03-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
