# Generated by Django 5.1.4 on 2025-03-30 17:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_agent_gender_alter_agent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('profile', 'Photo de profil'), ('cover', 'Photo de couverture'), ('animation', "Photo d'animation")], default='profile', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='agent_photos/', validators=[accounts.models.validate_image]),
        ),
    ]
